name: Generate xml sitemap

on:
  push:
    branches: [ guidelines ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: ./

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
        mv sitemap.xml sitemap.xml.tmp
        git config user.email swann.martineau@iala-aism.org
        git config user.name AdminSwann
        git fetch
        git checkout guidelines
        mv sitemap.xml.tmp sitemap_guidelines.xml
        git add sitemap_guidelines.xml
        git commit -m "New sitemaps"
        git push
