# This is a basic workflow to help you get started with Actions

name: Generate Sitemap

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: generate-sitemap
        uses: cicirello/generate-sitemap@v1.9.1
        with:
          # The url of your webpage
          base-url-path: https://github.com/AdminSwann/IALA_TEST/main/
          additional-extensions: txt
          
      - name: generate-mrn-map
        uses: AdminSwann/IALA_TEST_action@0.0.3
        with:
          base-url-path: https://github.com/AdminSwann/IALA_TEST/main/
            
      - run: |
          mv sitemap.xml sitemap.xml.tmp
          mv mrn-map.json mrn-map.json.tmp
          git config user.email swann.martineau@iala-aism.org
          git config user.name AdminSwann
          git fetch
          git checkout sitemap
          mv sitemap.xml.tmp sitemap.xml
          mv mrn-map.json.tmp mrn-map.json
          git add sitemap.xml mrn-map.json
          if [[ -z $(git --no-pager diff HEAD) ]]; then exit 0; fi
          git commit -m "New sitemaps"
          git push
        shell: bash
