name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://github.com/AdminSwann/IALA_TEST/main
        additional-extensions: doc docx ppt pptx xls xlsx

    - name: Output stats
            
      run: |
          mv sitemap.xml sitemap.xml.tmp
          git config user.email swann.martineau@iala-aism.org
          git config user.name AdminSwann
          git fetch
          git checkout sitemap
          mv sitemap.xml.tmp sitemap.xml
          git add sitemap.xml
          if [[ -z $(git --no-pager diff HEAD) ]]; then exit 0; fi
          git commit -m "New sitemaps"
          git push
          shell: bash
