name: Generate xml sitemap recommendations

on:
  push:
    branches: [ recommendations ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap recommendations

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap_guidelines
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: ./

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
        mv sitemap_recommendations.xml sitemap_recommendations.xml.tmp
        git config user.email swann.martineau@iala-aism.org
        git config user.name AdminSwann
        git fetch
        git checkout recommendations
        mv sitemap_recommendations.xml.tmp sitemap_recommendations.xml
        git add sitemap_recommendations.xml
        git commit -m "New sitemas"
        git push
